name: Release
on:
  release:
    types: [published]
jobs:
  release:
    uses: Solvely-Colin/ci-template/.github/workflows/release.yml@v1
    with:
      package-name: '@solvely/quorum'
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
